version: '3.1'

services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: spolyr
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./_mongo-volume:/data/db