/*
 * Spolyr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Model401Unauthorized struct {
	Code int32 `json:"code"`

	Message string `json:"message"`
}

// AssertModel401UnauthorizedRequired checks if the required fields are not zero-ed
func AssertModel401UnauthorizedRequired(obj Model401Unauthorized) error {
	elements := map[string]interface{}{
		"code":    obj.Code,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseModel401UnauthorizedRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Model401Unauthorized (e.g. [][]Model401Unauthorized), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseModel401UnauthorizedRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aModel401Unauthorized, ok := obj.(Model401Unauthorized)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertModel401UnauthorizedRequired(aModel401Unauthorized)
	})
}
