/*
 * Spolyr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TrackDetail struct {
	SpotifyId string `json:"spotifyId"`

	Title string `json:"title"`

	Album string `json:"album,omitempty"`

	CoverImage string `json:"coverImage,omitempty"`

	PreviewURL string `json:"previewURL,omitempty"`

	Artists []string `json:"artists,omitempty"`

	HasLyrics bool `json:"hasLyrics"`

	Language string `json:"language,omitempty"`

	Lyrics string `json:"lyrics"`

	LyricsImportErrorCount int32 `json:"lyricsImportErrorCount"`
}

// AssertTrackDetailRequired checks if the required fields are not zero-ed
func AssertTrackDetailRequired(obj TrackDetail) error {
	elements := map[string]interface{}{
		"spotifyId":              obj.SpotifyId,
		"title":                  obj.Title,
		"hasLyrics":              obj.HasLyrics,
		"lyrics":                 obj.Lyrics,
		"lyricsImportErrorCount": obj.LyricsImportErrorCount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseTrackDetailRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TrackDetail (e.g. [][]TrackDetail), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTrackDetailRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTrackDetail, ok := obj.(TrackDetail)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTrackDetailRequired(aTrackDetail)
	})
}
