/*
 * Spolyr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Model404NotFound struct {
	Code int32 `json:"code"`

	Message string `json:"message"`
}

// AssertModel404NotFoundRequired checks if the required fields are not zero-ed
func AssertModel404NotFoundRequired(obj Model404NotFound) error {
	elements := map[string]interface{}{
		"code":    obj.Code,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseModel404NotFoundRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Model404NotFound (e.g. [][]Model404NotFound), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseModel404NotFoundRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aModel404NotFound, ok := obj.(Model404NotFound)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertModel404NotFoundRequired(aModel404NotFound)
	})
}
