/*
 * Spolyr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OAuthUserInfo struct {
	DisplayName string `json:"displayName,omitempty"`

	AvatarUrl string `json:"avatarUrl,omitempty"`
}

// AssertOAuthUserInfoRequired checks if the required fields are not zero-ed
func AssertOAuthUserInfoRequired(obj OAuthUserInfo) error {
	return nil
}

// AssertRecurseOAuthUserInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OAuthUserInfo (e.g. [][]OAuthUserInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOAuthUserInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOAuthUserInfo, ok := obj.(OAuthUserInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOAuthUserInfoRequired(aOAuthUserInfo)
	})
}
