/*
 * Spolyr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthLoginPostRequest struct {
	Code string `json:"code,omitempty"`
}

// AssertAuthLoginPostRequestRequired checks if the required fields are not zero-ed
func AssertAuthLoginPostRequestRequired(obj AuthLoginPostRequest) error {
	return nil
}

// AssertRecurseAuthLoginPostRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AuthLoginPostRequest (e.g. [][]AuthLoginPostRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuthLoginPostRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuthLoginPostRequest, ok := obj.(AuthLoginPostRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuthLoginPostRequestRequired(aAuthLoginPostRequest)
	})
}
