/*
 * Spolyr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserResponse struct {
	Username string `json:"username,omitempty"`

	Avatar string `json:"avatar,omitempty"`
}

// AssertUserResponseRequired checks if the required fields are not zero-ed
func AssertUserResponseRequired(obj UserResponse) error {
	return nil
}

// AssertRecurseUserResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserResponse (e.g. [][]UserResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserResponse, ok := obj.(UserResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserResponseRequired(aUserResponse)
	})
}
