/*
 * Spolyr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Lyrics struct {
	Lyrics string `json:"lyrics,omitempty"`
}

// AssertLyricsRequired checks if the required fields are not zero-ed
func AssertLyricsRequired(obj Lyrics) error {
	return nil
}

// AssertRecurseLyricsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Lyrics (e.g. [][]Lyrics), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLyricsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLyrics, ok := obj.(Lyrics)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLyricsRequired(aLyrics)
	})
}
